# Generated by Django 5.1.15 on 2026-06-14 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ageattestation",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="age_attestations",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="ageattestation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="age_attestations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saveditem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="saveditem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ageattestation",
            index=models.Index(fields=["email"], name="accounts_ag_email_666936_idx"),
        ),
        migrations.AddIndex(
            model_name="ageattestation",
            index=models.Index(
                fields=["attested_at"], name="accounts_ag_atteste_1b6644_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saveditem",
            unique_together={("user", "product")},
        ),
    ]
