# Generated by Django 5.1.15 on 2026-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#2f5d3a",
                        help_text="Storefront + admin primary color (hex, e.g. #2f5d3a).",
                        max_length=7,
                    ),
                ),
                (
                    "guarantee_copy",
                    models.CharField(
                        default="$100 Guarantee",
                        help_text="Short trust/guarantee text shown in the header.",
                        max_length=120,
                    ),
                ),
                (
                    "store_phone",
                    models.CharField(default="(512) 555-0142", max_length=32),
                ),
                (
                    "store_email",
                    models.EmailField(default="howdy@txballistics.com", max_length=254),
                ),
                (
                    "pickup_address",
                    models.TextField(
                        default="1487 Ranch Road\nDripping Springs, TX 78620",
                        help_text="Revealed to the customer after they place an order.",
                    ),
                ),
                (
                    "pickup_instructions",
                    models.TextField(
                        blank=True,
                        default="Bring a valid photo ID and the card used to order. We'll email you when your order is bagged and ready.",
                    ),
                ),
                (
                    "catalog_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Browse-only: hides cart/checkout and disables online ordering.",
                    ),
                ),
                (
                    "show_stock",
                    models.BooleanField(
                        default=False,
                        help_text="Show stock counts/badges across the storefront.",
                    ),
                ),
                (
                    "fishing_shipping_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="When on, fishing/tackle ships instead of pickup.",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4, default="0.0825", max_digits=5
                    ),
                ),
                (
                    "shipping_flat_rate",
                    models.DecimalField(decimal_places=2, default="7.99", max_digits=8),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2, default="35.00", max_digits=8
                    ),
                ),
                (
                    "active_payment_provider",
                    models.CharField(
                        default="manual",
                        help_text="Key of the active payment provider (e.g. 'manual').",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
