# Generated by Django 5.1.15 on 2026-06-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="reviews_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show customer reviews and allow shoppers to submit them.",
            ),
        ),
    ]
