#!/usr/bin/env python3
"""Generate mockup/js/data.js from data/ammo_pricing.csv.

The static GitHub Pages site is driven entirely by the real product catalog.
This script reads the same CSV that the Django `import_pricing` command uses and
emits a browser-loadable `window.PRODUCTS` array. Only real fields are emitted —
no fabricated brands, ratings, reviews, or stock counts.

Run: python scripts/build_mockup_data.py
"""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "data" / "ammo_pricing.csv"
OUT_PATH = ROOT / "mockup" / "js" / "data.js"

# Abbreviations to keep the caliber badge label short enough for the image tile.
ABBR = {
    "Winchester": "Win",
    "Magnum": "Mag",
    "Remington": "Rem",
    "Government": "Gov",
    "Creedmoor": "Creed",
    "Special": "Spl",
    "Bushmaster": "BM",
    "Blackout": "BLK",
    "Grendel": "Grendel",
    "Lapua": "Lapua",
    "Mauser": "Mauser",
    "Legend": "Legend",
}


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-")


def short_caliber(caliber: str) -> str:
    words = [ABBR.get(w, w) for w in caliber.split()]
    label = " ".join(words)
    # Keep the tile readable; trim very long labels.
    return label if len(label) <= 14 else label[:13].rstrip() + "…"


def parse_grain(*texts: str):
    for text in texts:
        m = re.search(r"(\d+)\s*gn", text)
        if m:
            return int(m.group(1))
    return None


def main() -> None:
    products = []
    seen = set()
    with CSV_PATH.open(newline="", encoding="utf-8-sig") as fh:
        for row in csv.DictReader(fh):
            name = (row.get("Product") or "").strip()
            if not name:
                continue
            base = slugify(name)
            pid = base
            n = 2
            while pid in seen:
                pid = f"{base}-{n}"
                n += 1
            seen.add(pid)

            caliber = (row.get("Caliber") or "").strip()
            products.append(
                {
                    "id": pid,
                    "category": (row.get("Category") or "").strip(),
                    "caliber": caliber,
                    "calShort": short_caliber(caliber),
                    "name": name,
                    "description": (row.get("Description") or "").strip(),
                    "grain": parse_grain(row.get("Description") or "", name),
                    "usage": (row.get("Usage") or "").strip(),
                    "cost": float(row.get("Cost") or 0),
                    "roundsPerBox": int(row.get("RoundsPerBox") or 0),
                    "costPerRound": float(row.get("CostPerRound") or 0),
                }
            )

    payload = json.dumps(products, indent=2, ensure_ascii=False)
    OUT_PATH.write_text(
        "/* AUTO-GENERATED by scripts/build_mockup_data.py — do not edit by hand. */\n"
        f"window.PRODUCTS = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(products)} products to {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
